In [3]:
5+2

7

In [4]:
lista=[0,1,2,3,4,5]

In [5]:
lista*2

[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]

In [6]:
lista2=["nombre","edad"]

In [7]:
lista[0]

0

In [8]:
lista2[0]

'nombre'

In [9]:
import numpy as np

In [12]:
a=np.zeros(10)

In [13]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
a+2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [15]:
a=5

In [16]:
b=34

In [17]:
print((a+b))

39


In [18]:
b=np.ones(10)

In [19]:
a+b

array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

In [20]:
a=np.zeros(10)

In [21]:
a+b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
a=np.zeros(10)
b=np.ones(10)
c=np.linspace(-10,10,10)
d=np.arange(-10,10,0.15)

In [23]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
c

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [28]:
d

array([-10.  ,  -9.85,  -9.7 ,  -9.55,  -9.4 ,  -9.25,  -9.1 ,  -8.95,
        -8.8 ,  -8.65,  -8.5 ,  -8.35,  -8.2 ,  -8.05,  -7.9 ,  -7.75,
        -7.6 ,  -7.45,  -7.3 ,  -7.15,  -7.  ,  -6.85,  -6.7 ,  -6.55,
        -6.4 ,  -6.25,  -6.1 ,  -5.95,  -5.8 ,  -5.65,  -5.5 ,  -5.35,
        -5.2 ,  -5.05,  -4.9 ,  -4.75,  -4.6 ,  -4.45,  -4.3 ,  -4.15,
        -4.  ,  -3.85,  -3.7 ,  -3.55,  -3.4 ,  -3.25,  -3.1 ,  -2.95,
        -2.8 ,  -2.65,  -2.5 ,  -2.35,  -2.2 ,  -2.05,  -1.9 ,  -1.75,
        -1.6 ,  -1.45,  -1.3 ,  -1.15,  -1.  ,  -0.85,  -0.7 ,  -0.55,
        -0.4 ,  -0.25,  -0.1 ,   0.05,   0.2 ,   0.35,   0.5 ,   0.65,
         0.8 ,   0.95,   1.1 ,   1.25,   1.4 ,   1.55,   1.7 ,   1.85,
         2.  ,   2.15,   2.3 ,   2.45,   2.6 ,   2.75,   2.9 ,   3.05,
         3.2 ,   3.35,   3.5 ,   3.65,   3.8 ,   3.95,   4.1 ,   4.25,
         4.4 ,   4.55,   4.7 ,   4.85,   5.  ,   5.15,   5.3 ,   5.45,
         5.6 ,   5.75,   5.9 ,   6.05,   6.2 ,   6.35,   6.5 ,   6.65,
      

In [31]:
import matplotlib.pyplot as plt


ModuleNotFoundError: No module named 'matplotlib'

In [32]:
x=np.arange(-2np*pi,2*np.pi,0.01)
y=np.cos(x)
plt(x,y)

SyntaxError: invalid syntax (4029049726.py, line 1)